# Copyright 2024 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: "Setup Rust build"
description: "Common steps before running a Rust/Cargo task"

runs:
    using: "composite"
    steps:
        - name: Setup CI caching
          uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
          with:
              save-if: ${{ github.ref == 'refs/heads/main' }}

        - name: Install additional tools (Mac-only)
          if: runner.os == 'macOS'
          shell: bash
          run: brew install coreutils

        - name: Install additional tools (Linux-only)
          if: runner.os == 'Linux'
          shell: bash
          run: |
            sudo apt-get update
            sudo apt-get install -qy binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

        - name: Setup Rust and Cargo plugins
          shell: bash
          run: ./krabby.sh setup
