# Copyright 2024 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: "Setup Rust build"
description: "Common steps before running a Rust/Cargo task"

runs:
    using: "composite"
    steps:
        - name: Setup CI caching
          uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3
          with:
              save-if: ${{ github.ref == 'refs/heads/main' }}

        - name: Install asdf
          uses: asdf-vm/actions/setup@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3.0.2

        - name: Install local required tools
          shell: bash
          run: ./scripts/install-requirements.sh

        - name: Install additional tools (Mac-only)
          if: runner.os == 'macOS'
          shell: bash
          run: brew install coreutils

        - name: Install additional tools (Linux-only)
          if: runner.os == 'Linux'
          shell: bash
          run: sudo apt-get install -qy binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

        - name: Setup Rust and Cargo plugins
          shell: bash
          run: just setup
