[advisories]
ignore = [
    # Both better-panic and human-panic depend
    # indirectly on
    # https://github.com/jonas-schievink/adler
    # which is no longer maintened
    "RUSTSEC-2025-0056"
]

[licenses]
confidence-threshold = 0.95
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-DFS-2016",
    "BSD-3-Clause",
    "MPL-2.0",
    "Zlib"
]
