# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: "Docs"

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  ghpages-deploy:
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout source
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Prepare documentation assets
        uses: dotanuki-labs/github-actions/foss/prepare-ghpages@dea31f3c616e7d3057a55f71a56c3259218f4d1f # main

      - name: Deploy assets to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
